services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.4.2

install:
  - netstat -anp tcp | grep 5432
  - docker-compose pull
  - docker-compose build

script:
  - echo 'test'
  - ls -al
  - docker-compose run php ls -al

