services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.4.2

install:
  - sudo service postgresql stop
  - bin/install

script:
  - bin/tests/test

after_success:
  - travis_retry docker-compose exec php vendor/bin/php-coveralls -v

