services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.4.2

install:
  -  docker-compose ps
  - docker-compose up
#  -  bin/install

script:
  - echo 'test'
  - ls -al
#  - docker-compose exec php ls -al

