services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.4.2

before_install:
  - docker-compose pull
  - docker-compose build
  - docker-compose up -d

install:
  -  bin/composer install

script:
  - echo 'test'
  - ls -al
  - docker-compose exec php ls -al

