language: php

services:
  - docker

install:
  - sudo service postgresql stop
  - docker-compose --version
  - docker-compose exec --help
  - docker-compose run --help
#  - bin/install
#
#script:
#  - bin/tests/test
#
#after_success:
#  - travis_retry docker-compose exec -e TRAVIS_JOB_ID="$TRAVIS_JOB_ID" -e TRAVIS_BRANCH="$TRAVIS_BRANCH" -e TRAVIS="$TRAVIS" php vendor/bin/php-coveralls -v

