tasks:
    path: /tasks
    controller: App\Controller\TaskController::posts
    methods: GET

createTask:
    path: /tasks
    controller: App\Controller\TaskController:createPost
    methods: POST

updateTask:
    path: /tasks/{uuid}
    controller: App\Controller\TaskController:updatePost
    methods: PUT
