tasks:
    path: /tasks
    controller: App\Controller\TaskController::tasks
    methods: GET

createTask:
    path: /tasks
    controller: App\Controller\TaskController:createTask
    methods: POST

updateTask:
    path: /tasks/{uuid}
    controller: App\Controller\TaskController:updateTask
    methods: PUT

task:
    path: /tasks/{uuid}
    controller: App\Controller\TaskController:task
    methods: [GET]
